services:
  ragapp:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    command: uvicorn 4_rest_app:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
    depends_on:
      - ollama
    networks:
      - ollama-docker
      
  ollama:
    build:
      context: ./
      dockerfile: Dockerfile-Ollama
    volumes:
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 7869:11434
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  ollama-docker:
    external: false